---
title: "Workshop - Day 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

August 12, 2019 

## 1. [Spreadsheets](./01-spreadsheets.html)
(~30 minutes)

*  Implement best practices in data table formatting.
*  Identify and address common formatting mistakes.

Download the data for the spreadsheet exercise [here](https://ndownloader.figshare.com/files/2252083).

## 2. [Installing R packages](./02-packages.html)
(~15 minutes)

*  Understand what an R package is and how to install and load them.
*  Install the <b>tidyverse</b> and <b>ggplot2</b> packages.
 
## 3. [R basics](./03-rbasics.html)
(~60 minutes)

*  Assign values to objects in R.   
*  Learn how to name objects   
*  Use comments to inform script.   
*  Solve simple arithmetic operations in R.   
*  Call functions and use arguments to change their default options.   
*  Inspect the content of vectors and manipulate their content.   
*  Subset and extract values from vectors.   
*  Analyze vectors with missing data.

## 4. [Starting with data](./04-dataframes.html)
(~60 minutes)

*  Load external data into R with the `read.csv()` function.
*  Describe what an R data frame is.
*  Learn the properties of a factor and how to reorder them.
*  Subset values from data frames.

## 5. [Conditional statements and loops](./05-ifelsefor.html)
(~15 minutes)

*  Write an if...else statement.
*  Write a for loop to modify a data frame.

## 6. [Manipulating data in the tidyverse](./06-tidyr.html)
(~90 minutes)

*  Describe what a tibble is and how it differs from a data frame.
*  Describe what the `tidyr` package in R is used for.
*  Apply commonn `tidyr` functions to tidy data in R.
*  Describe what the `dplyr` package in R is used for.
*  Apply common `dplyr` functions to manipulate data in R.
*  Employ the ‘pipe’ operator to link together a sequence of functions.
*  Employ the ‘split-apply-combine’ concept to split the data into groups, apply analysis to each group, and combine the results.


