

<!-- <div class="wrapper"> -->
<!-- <a href="https://alanaschick.github.io/Rbootcamp2019/Schedule.html" class="button button1">Schedule</a> -->
<!-- </div> -->

<p class="big"> Welcome to the R bootcamp for biologists course website! </p>

<div class="center">
<h32> (August 12-14 at Foothills Medical Campus) </h32>
</div>

<br> 

## About this course
<p>

This course is offered by the <b>International Microbiome Centre</b> at the University of Calgary. The purpose of this course is to teach scientists (students, postdocs, PIs) in the biological and medical sciences to use R for typical data analysis tasks they might encounter routinely. This includes sequence analysis and other bioinformatics tasks.
<i> No prior knowledge of R is expected and workshop attendees can expect to come away with a skill set that is immediately translatable to their respective data tasks.</i></p>

<br>

## Format

<p>
To maximize the R skills and confidence attendees gain from this workshop, we have chosen to combine online learning materials with actual instruction days. 
<br>
<p>
We will use [datacamp's](https://www.datacamp.com/home) virtual classroom tool to train participants in basic R. About three weeks prior to the workshop, each attendee will receive a datacamp account with a list of assigned courses and assignments. Progress of each student will be monitored by the instructors. Prior to the workshop a Q &A session will be organized to review installation of R and RStudio and the Datacamp material.<font color="red"> Attendees will need to spend 4-6 hours on course material every week.</font> 
</p>
<p>
On the instruction days of the workshop, the knowledge gained from course work will be used to complete a biologialy relevant project.  </p>

<br>

## What you will learn 

At the end of the workshop you will able to:

* Install and update R
* Use the Rstudio IDE
* Import a wide variety of data types into R
* Understand the basic data types: integer, numeric, logical, character
* Understand R’s basic data structures: vector, matrix, list, data.frame
* Manipulate data structures by subsetting and indexing
* Manipulate data with tidyverse
* Make plots with ggplot2
* Understand some common R errors and how to deal with them
* Find and evaluate R packages needed for a particular analysis

<br>

## Fees

The fee for this course is 250 CAD.

<br>

## Register

<font color="red"> This course is currently at capacity. If you would like to put your name on a list to be notified if we offer this workshop again in the future, please use</font> <a href="https://forms.gle/f8m7vBjRUgqmiDxE8"> this link.</a>