<br>
<br>
<p>
Before the actual course days (8-10 January), we have organized  Q and A sessions on December 15th and 21st. These sessions are mandatory and be very helpful in getting you started and finishing the online courses on time. 

<br>
<p>


## Schedule

*  <b>Dec 15: 1/2 day session (10 am - 12pm, ROOM HSC G382 VC) </b> <a href="https://wcmcbioinformatics.github.io/Rbootcamp2018/Session1.html">Click here for details </a> 
    + Meet and Greet 
    + Rstudio IDE intro
    + project discussion, i.e. what type of project would they like

<br>
<font color="blue">

*  Dec 15 - 21: Datacamp course to be completed before December 21st session <a href="https://wcmcbioinformatics.github.io/Rbootcamp2018/code/tidyverse.html">Click here for details </a> 
    + Introduction to the Tidyverse

</font>

<br>

* <b>Dec 21: 1/2 day session (10 am - 12 pm, ROOM HSC G384)</b>
    + tidyverse practice session with a dataset

<br>

<font color="blue">

* Dec 22 - Jan 8: Datacamp courses to be completed before January 8th session
    + Introduction to R 
    + ggplot part 1

</font>

<br>

* <b>Jan 8: All day session (10 am - 4 pm ,ROOM HSC G382 VC) </b> <a href="https://wcmcbioinformatics.github.io/Rbootcamp2018/Revision_session.html">Click here for details </a>
    + AM: Review and practice Intro to R
    + PM: New concepts like statement controls, loops, functions and tidyr functions

<br>

* <b>Jan 9: Project day (10 am - 4 pm ,ROOM HSC G382 VC)</b>
    + [Project Info](https://wcmcbioinformatics.github.io/Rbootcamp2018/project/project.html)
    + [Data set](https://wcmcbioinformatics.github.io/Rbootcamp2018/project/data/Brauer2008_DatSet1.tds)

<br>

* <b>Jan 10: Project day (10 am - 4 pm ,ROOM HSC G382 VC)</b>
    + TBA


