---
title: "Tidy Genomics"
output: 
  html_document:
    css: ../style.css
---

## Introduction

The data we're going to work with comes from a yeast microarray experiment [(Brauer, 2008)](http://www.molbiolcell.org/content/19/1/352.abstract) where the authors measured gene expression in 36 chemostat cultures where growth was limited by one of six nutrients (glucose, ammonium, sulfate, phosphate, uracil, or leucine) at 3 different growth rates.   

The R world is full of niche tools designed for a specific problem or data type.  This is particularly true for Bioconductor and genomics analysis.  RNA-seq is a good example where all data import, analysis, and even plotting is done with custom packages and functions designed for gene expression data. Analysis of microbiome data with phyloseq is another example.  Now this is not a bad thing and can enable simple, rapid analysis.  Yet the point of learning a programming language like R is so you can take back control of your analysis and put the tools to work for your specific problem.  

For this project we're going to take some genomic data and pull it out of the context that it's usually analyzed in.  Bioconductor has a plethora of tools for analyzing microarray data and the `limma` package is by far the most comprehensive and useful.  However, for our project we're going to take microarray data that has already been processed and instead use it with data analysis tools that we've been learning.  

The take-away from this project to make the tools work for you instead of you working for them.  Data, genomic or not, is still data and we can use the tools available to us in R to gain valuable insights.


## Task 1: Data import and examination

The first task of almost all analysis is to get the data into R and spend a little time understanding it's structure.  Although you may be tempted to rush into an analysis it pays to take a bit of time to understand what you are working with and do some cleaning before you dive in too deep.  This is important help you avoid costly mistakes and wasted time downstream.  

The data file you'll be using is `Brauer2008_DataSet1.tds` and although it is pre-processed it will still need some work to get it ready to use.

Your goal is get the data loaded into R and answer the following questions:

* How many rows and columns are there?
* What do the rows and columns represent?
* On first glimpse do the column datatypes look correct?
* What about column names? 
* Is this data tidy?  Why or why not?  

As you look through the data start thinking about what steps you'll need to get it into a workable state.  


## Task 2: Data Tidying

Never underestimate the amount of time and effort it will take to tame a wild dataset into something usable.  Even if someone has already processed and "cleaned" the data before you (such as our current dataset) it is likely that you will need to spend some time fiddling with it for your particular needs (or for a particular function you want to use).  

You've learned about the tidy data concepts, now it's time to put them into practice. The first and most important step is decide what, if any tidying needs to be done. Recall that:

1. Each variable forms a column.
2. Each observation forms a row.
2. Each type of observational unit forms a table.

Questions to answer:

* Which column contains multiple variables?  Split it up so each column represents a single variable.
* The `GWEIGHT`, `GID`, and `YORF` columns we also won't need so you can get rid of those.
* What's wrong with the column names?  How can you fix that?
* Check again: do you have any columns that have multiple variables?  Be sure to fix any before you move on.

Try to code all the cleaning steps as a single pipeline.  The `separate()` and `gather()` functions from the tidyr package are a good place to start to accomplish these tasks.  

**Bonus:** Your cleaning steps may have left some variables with extra white space at the end.  Using `dplyr::mutate_each()` and a certain function from the `stringr` package see if you can clean these up.


## Task 3: Plots

Whew! Alright, that's done, but now you might asking why spend all that time cleaning up the data.  Hopefully you should be able to answer that question by now but moving on to making some plots will help make it even more clear.

In a typical analysis you wouldn't necessarily know which gene(s) to start looking at and would want to start with some more exploratory analysis.  However, to practice our plotting and analysis let's focus on a few pre-picked genes and pathways.

* Filter your now cleaned data to contain only the gene LEU1.
* Make a plot of the expression of this gene at various growth rates.  Use colour to distinguish the different nutrients.
* What are some conclusions you can make from this data?
* What biological process is LEU1 classified as?
* Filter your cleaned data for all genes that are in the same biological process as LEU!.
* Make a plot of these genes, the same as you had for LEU1 but faceted by gene.
* Do any of the other genes follow the same pattern as LEU1?  

